CREATE TABLE cliente (
    id_cliente NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nome_cliente VARCHAR2(100) NOT NULL,
    cpf_cliente VARCHAR2(11) NOT NULL,
    telefone_cliente VARCHAR2(15) NOT NULL,
    email_cliente VARCHAR2(100) NOT NULL,
    CONSTRAINT cliente_pk PRIMARY KEY (id_cliente),
    CONSTRAINT uk_cpf_cliente UNIQUE (cpf_cliente)
);