CREATE TABLE cliente (
                         id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome_cliente VARCHAR2(100) NOT NULL,
                         cpf_cliente VARCHAR2(14) NOT NULL UNIQUE,
                         telefone_cliente VARCHAR2(15) NOT NULL,
                         email_cliente VARCHAR2(100) NOT NULL
);

CREATE TABLE empresa (
                         id_empresa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome_empresa VARCHAR2(50) NOT NULL,
                         cnpj VARCHAR2(14) NOT NULL UNIQUE
);

CREATE TABLE localizacao (
                             id_localizacao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             status_loc NUMBER(5) NOT NULL,
                             data_hora TIMESTAMP NOT NULL,
                             zona_virtual VARCHAR2(50) NOT NULL,
                             latitude NUMBER(10,6) NOT NULL,
                             longitude NUMBER(10,6) NOT NULL
);

CREATE TABLE auditoria_moto (
                                id_audit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_name VARCHAR2(255),
                                operacao VARCHAR2(10),
                                data_hora TIMESTAMP,
                                old_values CLOB,
                                new_values CLOB
);
