CREATE TABLE empresa (
    id_empresa NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nome_empresa VARCHAR2(50) NOT NULL,
    cnpj VARCHAR2(14) NOT NULL,
    CONSTRAINT empresa_pk PRIMARY KEY (id_empresa),
    CONSTRAINT uk_cnpj UNIQUE (cnpj)
);