CREATE TABLE filial (
                        id_filial   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome_filial VARCHAR2(50)  NOT NULL,
                        cidade      VARCHAR2(50)  NOT NULL,
                        estado      VARCHAR2(2)   NOT NULL,
                        pais        VARCHAR2(50)  NOT NULL,
                        endereco    VARCHAR2(100) NOT NULL,
                        empresa_id  NUMBER        NOT NULL,
                        CONSTRAINT fk_empresa
                            FOREIGN KEY (empresa_id)
                                REFERENCES empresa (id_empresa)
);

CREATE TABLE funcionario (
                             id_func              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nome_func            VARCHAR2(100) NOT NULL,
                             cpf_func             VARCHAR2(11)  NOT NULL UNIQUE,
                             telefone_func        VARCHAR2(15)  NOT NULL,
                             email_func           VARCHAR2(100) NOT NULL UNIQUE,
                             password             VARCHAR2(255) NOT NULL,
                             cargo                NUMBER(1)     NOT NULL,
                             reset_password_token VARCHAR2(255),
                             token_expiry_date    TIMESTAMP,
                             filial_id            NUMBER        NOT NULL,
                             CONSTRAINT fk_filial_func
                                 FOREIGN KEY (filial_id)
                                     REFERENCES filial (id_filial)
);

CREATE TABLE operador (
                          id_operador  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome_opr     VARCHAR2(100) NOT NULL,
                          cpf_opr      VARCHAR2(11)  NOT NULL UNIQUE,
                          telefone_opr VARCHAR2(14)  NOT NULL,
                          email_opr    VARCHAR2(100) NOT NULL,
                          filial_id    NUMBER        NOT NULL,
                          CONSTRAINT fk_filial_opr
                              FOREIGN KEY (filial_id)
                                  REFERENCES filial (id_filial)
);

CREATE TABLE patio (
                       id_patio      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nome_patio    VARCHAR2(50) NOT NULL,
                       tamanho_patio VARCHAR2(50) NOT NULL,
                       andar         VARCHAR2(1)  NOT NULL,
                       filial_id     NUMBER       NOT NULL,
                       CONSTRAINT fk_filial_patio
                           FOREIGN KEY (filial_id)
                               REFERENCES filial (id_filial)
);

CREATE TABLE locacao (
                         id_locacao     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         data_inicio    DATE        NOT NULL,
                         data_fim       DATE        NOT NULL,
                         status_locacao NUMBER(1)   NOT NULL,
                         cliente_id     NUMBER      NOT NULL,
                         CONSTRAINT fk_cliente_locacao
                             FOREIGN KEY (cliente_id)
                                 REFERENCES cliente (id_cliente)
);

CREATE TABLE moto (
                      id_moto         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      placa           VARCHAR2(10)  NOT NULL UNIQUE,
                      modelo          VARCHAR2(50)  NOT NULL,
                      ano_fabricacao  NUMBER        NOT NULL,
                      status_moto     NUMBER(1)     NOT NULL,
                      locacao_id      NUMBER,
                      localizacao_id  NUMBER,
                      CONSTRAINT fk_locacao_moto
                          FOREIGN KEY (locacao_id)
                              REFERENCES locacao (id_locacao),
                      CONSTRAINT fk_localizacao_moto
                          FOREIGN KEY (localizacao_id)
                              REFERENCES localizacao (id_localizacao)
);

CREATE TABLE vaga (
                      id_vaga     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      status_vaga NUMBER(1)   NOT NULL,
                      patio_id    NUMBER      NOT NULL,
                      moto_id     NUMBER      UNIQUE,
                      fileira     VARCHAR2(1) NOT NULL,
                      coluna      VARCHAR2(1) NOT NULL,
                      CONSTRAINT fk_patio_vaga
                          FOREIGN KEY (patio_id)
                              REFERENCES patio (id_patio),
                      CONSTRAINT fk_moto_vaga
                          FOREIGN KEY (moto_id)
                              REFERENCES moto (id_moto)
);
