--V4__create-all-tables.sql

CREATE TABLE filial (
    id_filial NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nome_filial VARCHAR2(50) NOT NULL,
    cidade VARCHAR2(50) NOT NULL,
    estado VARCHAR2(2) NOT NULL,
    pais VARCHAR2(50) NOT NULL,
    endereco VARCHAR2(100) NOT NULL,
    empresa_id NUMBER(19,0) NOT NULL,
    CONSTRAINT filial_pk PRIMARY KEY (id_filial),
    CONSTRAINT fk_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id_empresa)
);


CREATE TABLE funcionario (
    id_func NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nome_func VARCHAR2(100) NOT NULL,
    cpf_func VARCHAR2(11) NOT NULL,
    cargo VARCHAR2(50) NOT NULL,
    telefone_func VARCHAR2(15) NOT NULL,
    email_func VARCHAR2(100) NOT NULL,
    filial_id NUMBER(19,0) NOT NULL,
    CONSTRAINT funcionario_pk PRIMARY KEY (id_func),
    CONSTRAINT fk_filial_func FOREIGN KEY (filial_id) REFERENCES filial(id_filial),
     CONSTRAINT uk_cpf_func UNIQUE (cpf_func)
);

CREATE TABLE operador (
    id_operador NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nome_opr VARCHAR2(100) NOT NULL,
    cpf_opr VARCHAR2(11) NOT NULL,
    telefone_opr VARCHAR2(14) NOT NULL,
    email_opr VARCHAR2(100) NOT NULL,
    filial_id NUMBER(19,0) NOT NULL,
    CONSTRAINT operador_pk PRIMARY KEY (id_operador),
    CONSTRAINT fk_filial_opr FOREIGN KEY (filial_id) REFERENCES filial(id_filial),
     CONSTRAINT uk_cpf_opr UNIQUE (cpf_opr)
);


CREATE TABLE patio (
    id_patio NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nome_patio VARCHAR2(50) NOT NULL,
    tamanho_patio VARCHAR2(50) NOT NULL,
    andar VARCHAR2(1) NOT NULL,
    filial_id NUMBER(19,0) NOT NULL,
    CONSTRAINT patio_pk PRIMARY KEY (id_patio),
    CONSTRAINT fk_filial_patio FOREIGN KEY (filial_id) REFERENCES filial(id_filial)
);

CREATE TABLE cliente_locacao (
    id_locacao NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    status_locacao VARCHAR2(20) NOT NULL,
    cliente_id NUMBER(19,0) NOT NULL,
    CONSTRAINT locacao_pk PRIMARY KEY (id_locacao),
    CONSTRAINT fk_cliente_locacao FOREIGN KEY (cliente_id) REFERENCES cliente(id_cliente)
);


CREATE TABLE localizacao (
    id_localizacao NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    status_loc VARCHAR2(20) NOT NULL,
    data_hora TIMESTAMP NOT NULL,
    zona_virtual VARCHAR2(50) NOT NULL,
    latitude NUMBER(10,8) NOT NULL,
    longitude NUMBER(11,8) NOT NULL,
    CONSTRAINT localizacao_pk PRIMARY KEY (id_localizacao)
);


CREATE TABLE moto (
    id_moto NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    placa VARCHAR2(10) NOT NULL,
    modelo VARCHAR2(50) NOT NULL,
    ano_fabricacao NUMBER(4) NOT NULL,
    status_moto VARCHAR2(20) NOT NULL,
    locacao_id NUMBER(19,0) NOT NULL,
    localizacao_id NUMBER(19,0) NOT NULL,
    CONSTRAINT moto_pk PRIMARY KEY (id_moto),
    CONSTRAINT fk_locacao_moto FOREIGN KEY (locacao_id) REFERENCES cliente_locacao(id_locacao),
    CONSTRAINT fk_localizacao_moto FOREIGN KEY (localizacao_id) REFERENCES localizacao(id_localizacao),
    CONSTRAINT uk_placa UNIQUE (placa)
);


CREATE TABLE vaga (
    id_vaga NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    status_vaga VARCHAR2(20) NOT NULL,
    patio_id NUMBER(19,0) NOT NULL,
    moto_id NUMBER(19,0) NOT NULL,
    fileira VARCHAR2(1) NOT NULL,
    coluna VARCHAR2(1) NOT NULL,
    CONSTRAINT vaga_pk PRIMARY KEY (id_vaga),
    CONSTRAINT fk_patio_vaga FOREIGN KEY (patio_id) REFERENCES patio(id_patio),
    CONSTRAINT fk_moto_vaga FOREIGN KEY (moto_id) REFERENCES moto(id_moto),
    CONSTRAINT uk_moto_vaga UNIQUE (moto_id)
);