DROP TABLE moto CASCADE CONSTRAINTS;

CREATE TABLE moto (
                      id_moto         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      placa           VARCHAR2(10) UNIQUE,
                      modelo          VARCHAR2(50) NOT NULL,
                      ano_fabricacao  NUMBER(4)    NOT NULL,
                      status_moto     NUMBER(1)    NOT NULL,
                      locacao_id      NUMBER       NOT NULL,
                      localizacao_id  NUMBER       NOT NULL,
                      CONSTRAINT moto_locacao_fk     FOREIGN KEY (locacao_id)     REFERENCES locacao (id_locacao),
                      CONSTRAINT moto_localizacao_fk FOREIGN KEY (localizacao_id) REFERENCES localizacao (id_localizacao),
                      CONSTRAINT moto_status_ck CHECK (status_moto IN (0, 1, 2))
);

INSERT INTO moto (placa, modelo, ano_fabricacao, status_moto, locacao_id, localizacao_id)
VALUES (
           'XYZ1A23',
           'Honda CG 160',
           2022,
           1,
           (SELECT id_locacao
            FROM locacao
            WHERE data_inicio = TO_DATE('2024-01-10', 'YYYY-MM-DD')
              AND cliente_id = (SELECT id_cliente FROM cliente WHERE cpf_cliente = '84406286098')),
           (SELECT id_localizacao FROM localizacao WHERE zona_virtual = 'Pátio SP')
       );

INSERT INTO moto (placa, modelo, ano_fabricacao, status_moto, locacao_id, localizacao_id)
VALUES (
           'ABC2B34',
           'Yamaha Fazer 250',
           2021,
           1,
           (SELECT id_locacao
            FROM locacao
            WHERE data_inicio = TO_DATE('2024-01-11', 'YYYY-MM-DD')
              AND cliente_id = (SELECT id_cliente FROM cliente WHERE cpf_cliente = '58556870074')),
           (SELECT id_localizacao FROM localizacao WHERE zona_virtual = 'Zona Sul SP')
       );

INSERT INTO moto (placa, modelo, ano_fabricacao, status_moto, locacao_id, localizacao_id)
VALUES (
           'DEF3C45',
           'Honda Biz 125',
           2020,
           0,
           (SELECT id_locacao
            FROM locacao
            WHERE data_inicio = TO_DATE('2024-01-10', 'YYYY-MM-DD')
              AND cliente_id = (SELECT id_cliente FROM cliente WHERE cpf_cliente = '84406286098')),
           (SELECT id_localizacao FROM localizacao WHERE zona_virtual = 'Pátio RJ')
       );

INSERT INTO moto (placa, modelo, ano_fabricacao, status_moto, locacao_id, localizacao_id)
VALUES (
           'GHI4D56',
           'Yamaha NMAX 160',
           2023,
           2,
           (SELECT id_locacao
            FROM locacao
            WHERE data_inicio = TO_DATE('2024-01-11', 'YYYY-MM-DD')
              AND cliente_id = (SELECT id_cliente FROM cliente WHERE cpf_cliente = '58556870074')),
           (SELECT id_localizacao FROM localizacao WHERE zona_virtual = 'Pátio SP')
       );

INSERT INTO moto (placa, modelo, ano_fabricacao, status_moto, locacao_id, localizacao_id)
VALUES (
           'JKL5E67',
           'Honda PCX 150',
           2019,
           0,
           (SELECT id_locacao
            FROM locacao
            WHERE data_inicio = TO_DATE('2024-01-10', 'YYYY-MM-DD')
              AND cliente_id = (SELECT id_cliente FROM cliente WHERE cpf_cliente = '84406286098')),
           (SELECT id_localizacao FROM localizacao WHERE zona_virtual = 'Zona Sul SP')
       );
