DROP TABLE IF EXISTS noticia;

CREATE TABLE noticia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    conteudo CLOB NOT NULL,
    data_publicacao DATE NOT NULL,
    autor VARCHAR(100) NOT NULL,
    categoria VARCHAR(50) NOT NULL
);

INSERT INTO noticia (titulo, conteudo, data_publicacao, autor, categoria) VALUES
('Nova Geração de Motos Elétricas Chega ao Brasil', 'A Mottu anunciou hoje o lançamento de sua nova linha de motos elétricas, prometendo mais autonomia e economia para os entregadores...', '2025-09-26', 'Equipe EasyMoto', 'TECNOLOGIA'),
('Dicas de Segurança para Entregas Noturnas', 'Com o aumento da demanda por entregas à noite, separamos algumas dicas essenciais para garantir a sua segurança...', '2025-09-25', 'João Especialista', 'SEGURANCA');